### ISSUE TITLE
Lock is not getting released using `waitAcquireLock`

### ISSUE THREAD

**Issue by divmgl** [mixmaxhq/redfour#16]
Is it necessary to use `acquireLock` followed by `waitAcquireLock`? Having an issue where a lock is released and the succeeding resource isn't receiving the publish call. I'm likely doing something wrong. I have a setup like this:

```js
function acquire(key) {
  return new Promise((resolve, reject) =>
    locks.waitAcquireLock(key, 1000, 1000, (err, lock) => { // Low TTL because of release issues
      if (err) return reject(err)
      return resolve(() => release(lock))
    })
  )
}

function release(lock, context) {
  return new Promise((resolve, reject) => {
    locks.releaseLock(lock, err => {
      if (err) reject(err)
      resolve()
    })
  })
}
```

This allows me to do:

```js
const release = await acquire('some_resource')
// ... some processing ...
await release()
```

But the lock is not getting properly released. Is it okay to use `waitAcquireLock` exclusively?

**Comment by divmgl** [comment]
After looking at the source it looks like `waitAcquireLock` just uses `acquireLock` and encapsulates the lock acquisition with a TTL implementation. Problem must be on my end.

**Comment by ttacon** [comment]
Correct:

> After looking at the source it looks like waitAcquireLock just uses acquireLock and encapsulates the lock acquisition with a TTL implementation.

Let us know if your troubles persist, would love to help get to the bottom of this!

**Comment by divmgl** [comment]
@ttacon does it make sense to use `new Lock` every time a lock is required or is using `new Lock`  once follow by subsequent `acquireLock` calls acceptable?

**Comment by divmgl** [comment]
@ttacon there were two issues:

1. I was using existing key names for the lock.
2. I was trying to acquire the same lock twice within the same application instance.
